trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - "README.md"
      - ".gitignore"

variables:
  - name: terraformVersion
    value: "latest"
  - name: serviceConnection
    value: "Your-Service-Connection-Name"
  - name: backendRG
    value: "Your-Backend-Resource-Group"
  - name: backendSA
    value: "Your-Backend-Storage-Account"
  - name: backendContainer
    value: "Your-Backend-Container"
  - name: projectName
    value: "Your-Project-Name"
  - name: backendKey
    value: "$(projectName).tfstate"

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Terraform
    jobs:
      - job: Deploy
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: $(terraformVersion)
            displayName: Terraform Installer

          - task: TerraformTaskV4@4
            displayName: Terraform Init
            inputs:
              provider: "azurerm"
              command: "init"
              commandOptions: "-reconfigure"
              backendServiceArm: $(serviceConnection)
              backendAzureRmResourceGroupName: $(backendRG)
              backendAzureRmStorageAccountName: $(backendSA)
              backendAzureRmContainerName: $(backendContainer)
              backendAzureRmKey: $(backendKey)

          - task: TerraformTaskV4@4
            displayName: Terraform Validate
            inputs:
              provider: "azurerm"
              command: "validate"

          - task: TerraformTaskV4@4
            displayName: Terraform Plan
            inputs:
              provider: "azurerm"
              command: "plan"
              environmentServiceNameAzureRM: $(serviceConnection)
              commandOptions: '-var-file="terraform.tfvars"'

          - task: TerraformTaskV4@4
            displayName: Terraform Apply
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
            inputs:
              provider: "azurerm"
              command: "apply"
              environmentServiceNameAzureRM: $(serviceConnection)
              commandOptions: '-auto-approve -var-file="terraform.tfvars"'
